<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="RSHOP" content="品络科技 - PinLuo.com">
<meta name=author content="品络科技 - PinLuo.com">
<title>品络科技 - PinLuo.com</title>
<style type="text/css">
<!--
.style1 {
	color: #000000;
	font-weight: bold;
}
-->
</style>
</head>
<body topmargin="0" leftmargin="0">
<table class="tableBorder" width="100%" height="28" border="0" cellpadding="0" cellspacing="0">
    <tr> 
      <td width="100%" background="Images/admin_topbg.gif">
        <div align="center">
          <table class="tableBorder" width="98%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <form name="form1"  method="post" action="Search.asp" target="_self">
      <td width="18%" align="right"><span class="style1"><span style="font-size: 9pt">后台搜索:&nbsp; </span> </span></td>
      <td width="12%" align="right"><select name="stype" class="input" >
          <option value="Music" selected>歌曲名称</option>
          <option value="Special">专辑名称</option>
          <option value="Singer">歌手姓名</option>
          <option value="User">站内用户</option>
        </select></td>
      <td width="37%" align="right"><input size=39 type="text" value="输入关键字" onClick="Javascript:this.value=''" onfocus=this.select() onmouseover=this.focus() name=keyword></td>
      <td width="6%"><input type="image" src="Images/Search.gif" align="middle" title="查询" id=Image1 name=Image1></td>
      <td width="27%"><a class=3d href="javascript:this.location.reload()" ><span class="style1"><span style="font-size: 9pt">刷新本页</span> </span></a></td>
    </form>
</table>

        </div>
      </td>
    </tr>
</table>
